// Code generated by protoc-gen-go.
// source: control.proto
// DO NOT EDIT!

/*
Package Report is a generated protocol buffer package.

It is generated from these files:
	control.proto
	data.proto
	manage.proto
	param.proto
	plc_status.proto

It has these top-level messages:
	ControlCommand
	Monitor
	Alter
	DataCommand
	ManageCommand
	Param
	PLCStataus
*/
package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControlCommand_CommandType int32

const (
	ControlCommand_CMT_INVALID               ControlCommand_CommandType = 0
	ControlCommand_CMT_REQ_RESTART           ControlCommand_CommandType = 3
	ControlCommand_CMT_REP_RESTART           ControlCommand_CommandType = 32771
	ControlCommand_CMT_REQ_DATA_DOWNLOAD     ControlCommand_CommandType = 7
	ControlCommand_CMT_REP_DATA_DOWNLOAD     ControlCommand_CommandType = 32775
	ControlCommand_CMT_REQ_DATA_QUERY        ControlCommand_CommandType = 8
	ControlCommand_CMT_REP_DATA_QUERY        ControlCommand_CommandType = 32776
	ControlCommand_CMT_REQ_BATCH_ADD_MONITOR ControlCommand_CommandType = 9
	ControlCommand_CMT_REP_BATCH_ADD_MONITOR ControlCommand_CommandType = 32777
	ControlCommand_CMT_REQ_BATCH_ADD_ALTER   ControlCommand_CommandType = 10
	ControlCommand_CMT_REP_BATCH_ADD_ALTER   ControlCommand_CommandType = 32778
	ControlCommand_CMT_REQ_RS232_GET_CONFIG  ControlCommand_CommandType = 17
	ControlCommand_CMT_REP_RS232_GET_CONFIG  ControlCommand_CommandType = 32785
	ControlCommand_CMT_REQ_RS232_SET_CONFIG  ControlCommand_CommandType = 18
	ControlCommand_CMT_REP_RS232_SET_CONFIG  ControlCommand_CommandType = 32786
	ControlCommand_CMT_REQ_RS485_GET_CONFIG  ControlCommand_CommandType = 33
	ControlCommand_CMT_REP_RS485_GET_CONFIG  ControlCommand_CommandType = 32801
	ControlCommand_CMT_REQ_RS485_SET_CONFIG  ControlCommand_CommandType = 34
	ControlCommand_CMT_REP_RS485_SET_CONFIG  ControlCommand_CommandType = 32802
	ControlCommand_CMT_REQ_GET_SERVER_ADDR   ControlCommand_CommandType = 4
	ControlCommand_CMT_REP_GET_SERVER_ADDR   ControlCommand_CommandType = 32772
	ControlCommand_CMT_REQ_SET_SERVER_ADDR   ControlCommand_CommandType = 5
	ControlCommand_CMT_REP_SET_SERVER_ADDR   ControlCommand_CommandType = 32773
)

var ControlCommand_CommandType_name = map[int32]string{
	0:     "CMT_INVALID",
	3:     "CMT_REQ_RESTART",
	32771: "CMT_REP_RESTART",
	7:     "CMT_REQ_DATA_DOWNLOAD",
	32775: "CMT_REP_DATA_DOWNLOAD",
	8:     "CMT_REQ_DATA_QUERY",
	32776: "CMT_REP_DATA_QUERY",
	9:     "CMT_REQ_BATCH_ADD_MONITOR",
	32777: "CMT_REP_BATCH_ADD_MONITOR",
	10:    "CMT_REQ_BATCH_ADD_ALTER",
	32778: "CMT_REP_BATCH_ADD_ALTER",
	17:    "CMT_REQ_RS232_GET_CONFIG",
	32785: "CMT_REP_RS232_GET_CONFIG",
	18:    "CMT_REQ_RS232_SET_CONFIG",
	32786: "CMT_REP_RS232_SET_CONFIG",
	33:    "CMT_REQ_RS485_GET_CONFIG",
	32801: "CMT_REP_RS485_GET_CONFIG",
	34:    "CMT_REQ_RS485_SET_CONFIG",
	32802: "CMT_REP_RS485_SET_CONFIG",
	4:     "CMT_REQ_GET_SERVER_ADDR",
	32772: "CMT_REP_GET_SERVER_ADDR",
	5:     "CMT_REQ_SET_SERVER_ADDR",
	32773: "CMT_REP_SET_SERVER_ADDR",
}
var ControlCommand_CommandType_value = map[string]int32{
	"CMT_INVALID":               0,
	"CMT_REQ_RESTART":           3,
	"CMT_REP_RESTART":           32771,
	"CMT_REQ_DATA_DOWNLOAD":     7,
	"CMT_REP_DATA_DOWNLOAD":     32775,
	"CMT_REQ_DATA_QUERY":        8,
	"CMT_REP_DATA_QUERY":        32776,
	"CMT_REQ_BATCH_ADD_MONITOR": 9,
	"CMT_REP_BATCH_ADD_MONITOR": 32777,
	"CMT_REQ_BATCH_ADD_ALTER":   10,
	"CMT_REP_BATCH_ADD_ALTER":   32778,
	"CMT_REQ_RS232_GET_CONFIG":  17,
	"CMT_REP_RS232_GET_CONFIG":  32785,
	"CMT_REQ_RS232_SET_CONFIG":  18,
	"CMT_REP_RS232_SET_CONFIG":  32786,
	"CMT_REQ_RS485_GET_CONFIG":  33,
	"CMT_REP_RS485_GET_CONFIG":  32801,
	"CMT_REQ_RS485_SET_CONFIG":  34,
	"CMT_REP_RS485_SET_CONFIG":  32802,
	"CMT_REQ_GET_SERVER_ADDR":   4,
	"CMT_REP_GET_SERVER_ADDR":   32772,
	"CMT_REQ_SET_SERVER_ADDR":   5,
	"CMT_REP_SET_SERVER_ADDR":   32773,
}

func (x ControlCommand_CommandType) String() string {
	return proto.EnumName(ControlCommand_CommandType_name, int32(x))
}
func (ControlCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ControlCommand struct {
	Uuid         string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Tid          uint64                     `protobuf:"varint,2,opt,name=tid" json:"tid,omitempty"`
	SerialNumber uint32                     `protobuf:"varint,3,opt,name=serial_number" json:"serial_number,omitempty"`
	Type         ControlCommand_CommandType `protobuf:"varint,4,opt,name=type,enum=Report.ControlCommand_CommandType" json:"type,omitempty"`
	Paras        []*Param                   `protobuf:"bytes,5,rep,name=paras" json:"paras,omitempty"`
}

func (m *ControlCommand) Reset()                    { *m = ControlCommand{} }
func (m *ControlCommand) String() string            { return proto.CompactTextString(m) }
func (*ControlCommand) ProtoMessage()               {}
func (*ControlCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ControlCommand) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ControlCommand) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *ControlCommand) GetSerialNumber() uint32 {
	if m != nil {
		return m.SerialNumber
	}
	return 0
}

func (m *ControlCommand) GetType() ControlCommand_CommandType {
	if m != nil {
		return m.Type
	}
	return ControlCommand_CMT_INVALID
}

func (m *ControlCommand) GetParas() []*Param {
	if m != nil {
		return m.Paras
	}
	return nil
}

func init() {
	proto.RegisterType((*ControlCommand)(nil), "Report.ControlCommand")
	proto.RegisterEnum("Report.ControlCommand_CommandType", ControlCommand_CommandType_name, ControlCommand_CommandType_value)
}

func init() { proto.RegisterFile("control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb1, 0xe3, 0x04, 0x3a, 0x26, 0xed, 0x32, 0x28, 0xe0, 0xd2, 0x16, 0x4c, 0x4e, 0x3e,
	0x45, 0x28, 0x05, 0x89, 0xeb, 0x62, 0x9b, 0x12, 0x29, 0x8d, 0xdd, 0xf5, 0x52, 0xc4, 0x69, 0x95,
	0x12, 0x1f, 0x22, 0x35, 0xb1, 0xe5, 0x3a, 0x87, 0xde, 0x2c, 0x01, 0xe2, 0xcf, 0x0d, 0x9e, 0x00,
	0x78, 0x07, 0xde, 0x0f, 0x99, 0xb0, 0x61, 0x6d, 0xe7, 0x64, 0xe9, 0xfb, 0xcd, 0x6f, 0x3c, 0xfa,
	0xa4, 0x85, 0xee, 0xbb, 0x64, 0x99, 0x67, 0xc9, 0xe5, 0x20, 0xcd, 0x92, 0x3c, 0xc1, 0x0e, 0x8b,
	0xd3, 0x24, 0xcb, 0x1f, 0x98, 0xe9, 0x34, 0x9b, 0x2e, 0xd6, 0x61, 0xff, 0x77, 0x07, 0x76, 0xdd,
	0xf5, 0x98, 0x9b, 0x2c, 0x16, 0xd3, 0xe5, 0x0c, 0x6f, 0x83, 0xb1, 0x5a, 0xcd, 0x67, 0x96, 0x66,
	0x6b, 0xce, 0x0e, 0x9a, 0xd0, 0xca, 0xe7, 0x33, 0x4b, 0xb7, 0x35, 0xc7, 0xc0, 0x1e, 0x74, 0xaf,
	0xe2, 0x6c, 0x3e, 0xbd, 0x14, 0xcb, 0xd5, 0xe2, 0x22, 0xce, 0xac, 0x96, 0xad, 0x39, 0x5d, 0x7c,
	0x02, 0x46, 0x7e, 0x9d, 0xc6, 0x96, 0x61, 0x6b, 0xce, 0xee, 0xb0, 0x3f, 0x58, 0xff, 0x68, 0x50,
	0xdd, 0x3b, 0xf8, 0xf7, 0xe5, 0xd7, 0x69, 0x8c, 0x87, 0xd0, 0x2e, 0xaf, 0xb8, 0xb2, 0xda, 0x76,
	0xcb, 0x31, 0x87, 0x5d, 0xa9, 0x84, 0xe5, 0x69, 0xfd, 0x1f, 0x6d, 0x30, 0xd5, 0xe9, 0x3d, 0x30,
	0xdd, 0x53, 0x2e, 0x46, 0x93, 0x73, 0x3a, 0x1e, 0x79, 0xe4, 0x06, 0xde, 0x85, 0xbd, 0x32, 0x60,
	0xfe, 0x99, 0x60, 0x7e, 0xc4, 0x29, 0xe3, 0xa4, 0x85, 0x3d, 0x19, 0x86, 0x9b, 0xf0, 0x7d, 0xa1,
	0xe3, 0x3e, 0xf4, 0xe4, 0xac, 0x47, 0x39, 0x15, 0x5e, 0xf0, 0x66, 0x32, 0x0e, 0xa8, 0x47, 0x6e,
	0xe2, 0x81, 0x44, 0x61, 0x0d, 0x7d, 0x2a, 0x74, 0xbc, 0x07, 0x58, 0xf1, 0xce, 0x5e, 0xfb, 0xec,
	0x2d, 0xb9, 0x85, 0x96, 0xcc, 0x43, 0x35, 0xff, 0x5c, 0xe8, 0x78, 0x04, 0xfb, 0xd2, 0x78, 0x41,
	0xb9, 0xfb, 0x4a, 0x50, 0xcf, 0x13, 0xa7, 0xc1, 0x64, 0xc4, 0x03, 0x46, 0x76, 0xf0, 0x91, 0xc4,
	0xe1, 0x16, 0xfc, 0xa5, 0xd0, 0xf1, 0x00, 0xee, 0x37, 0x7d, 0x3a, 0xe6, 0x3e, 0x23, 0x80, 0x47,
	0x12, 0x86, 0x0d, 0xf8, 0xb5, 0xd0, 0xf1, 0x10, 0xac, 0x4d, 0x23, 0xd1, 0xf0, 0x78, 0x28, 0x4e,
	0x7c, 0x2e, 0xdc, 0x60, 0xf2, 0x72, 0x74, 0x42, 0xee, 0xe0, 0x43, 0x49, 0xc3, 0x26, 0xfd, 0xb6,
	0xcd, 0x8e, 0xfe, 0x73, 0x6c, 0xda, 0x0a, 0xfd, 0x5e, 0xb7, 0x9f, 0x3e, 0x7f, 0xa6, 0x6e, 0x7f,
	0x5c, 0xb5, 0x6b, 0xf4, 0xe7, 0x36, 0x5b, 0xd9, 0xde, 0x6f, 0xda, 0x0a, 0xfd, 0x55, 0xed, 0xac,
	0xdc, 0x1b, 0xf9, 0xec, 0xdc, 0x67, 0x65, 0x37, 0x8c, 0x18, 0x6a, 0x67, 0x75, 0xf8, 0xa1, 0xea,
	0x46, 0x35, 0xdc, 0x56, 0xdd, 0x3a, 0xfc, 0x58, 0xe8, 0x17, 0x9d, 0xbf, 0xcf, 0xe7, 0xf8, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xd5, 0xfa, 0x8c, 0x64, 0x03, 0x00, 0x00,
}
